import type { Metadata } from "next";
import { Nanum_Myeongjo} from "next/font/google";
import "./globals.css";

const nanummyeongjo = Nanum_Myeongjo({
  variable: "--font-nanum-myeongjo",
  subsets: ["latin"],
  weight: ["400", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nanummyeongjo.variable}>
        {children}
      </body>
    </html>
  );
}
